### ISSUE TITLE
Add mObywatel

### ISSUE THREAD

**Issue by sbstn87** [Crazyphil/digitales-amt-liberator#10]
Hi,

would it be possible to add the Polish mObywatel app to the list of supported software?

Link:
https://play.google.com/store/apps/details?id=pl.nask.mobywatel

**Comment by sdrgeek** [comment]
I've added support in #11. Please test it.

**Comment by sbstn87** [comment]
Thank you, but can you please link to the APK? Sorry for the trouble, but I cannot see it there.

**Comment by sdrgeek** [comment]
[app-debug.zip](https://github.com/Crazyphil/digitales-amt-liberator/files/12477792/app-debug.zip)

**Comment by sbstn87** [comment]
I have downloaded and installed it, but it does not launch. It cannot be opened and it does not show on the list of available apps.

**Comment by sbstn87** [comment]
I have installed Magisk, but I have absolutely no idea how it works. So, I am sorry but I will not be able to test it.

**Comment by Crazyphil** [comment]
@sbstn87 You can find an installation instruction for Magisk [here](https://topjohnwu.github.io/Magisk/install.html). In the *Modules* section of the app (in the bottom menu) you can then install [LSPosed](https://github.com/LSPosed/LSPosed#install) by downloading the latest release ZIP file with Zygisk, touching the *Install from storage* button in Magisk und selecting the downloaded ZIP file. Finally, when you start LSPosed, you can again select the *Module archive* menu option, search for *E-Government Liberator* and install the latest version.

However, please note that you need a device with an unlocked bootloader, which voids the device's warranty and is not appropriate for the average user. If you feel not up to the task, you might want to consider looking for other options.

**Comment by sbstn87** [comment]
I have an unlocked bootloader and a custom ROM, but unfortunately I completely do not understand those instructions - what are the files they want to patch, etc. So I am sorry, but I will not be able to test it.

**Comment by sdrgeek** [comment]
@sbstn87 Ok, let's start again... You mentioned, that you installed magisk, so you should have root, right? If you don't, reboot to recovery and flash the [Magisk.apk](https://github.com/topjohnwu/Magisk/releases/download/v26.3/Magisk.v26.3.apk) (sideload the apk). After you restarted your phone, go into the Magisk app settings (top right) and enable Zygisk. Restart. When you go into the Magisk app, there should be a modules tab at the bottom. When you click on it, you should see a install from storage button on the top. Click on it. Install [this](https://github.com/LSPosed/LSPosed/releases/download/v1.9.1/LSPosed-v1.9.1-6990-zygisk-release.zip) zip file (I assume you already downloaded it on your phone, before you click on install from storage). Wait for the installation to finish, you will be prompted to restart your phone, restart. After that open Magisk and enable the LSPosed module (in the modules tab). If successfully installed, you should now have a silent notification "LSPosed loaded". Now try to install the apk I sent you earlier for testing. Click on the LSPosed notification, go the modules tab and click on the _E-Government Liberator_ app. Enable the module and select mObywatel. mObywatel should now work.

**Comment by MinekPo1** [comment]
works for me with LSPatch (the root checker was a false positive, ironic lol), so I assume it works.

**Comment by sdrgeek** [comment]
That's great news. Could you test the app beyond login? Do all features work as expected?

> the root checker was a false positive, ironic lol

Wdym? In testing, I had to bypass the root and bootloader checks. Ofc you won't get the errors if your device isn't modified.

**Comment by MinekPo1** [comment]
> That's great news. Could you test the app beyond login? Do all features work as expected?

yup, no issues, though I can't test all of the app since they don't apply to me (for example I don't drive and that seems like a large part of the app)

> Wdym? In testing, I had to bypass the root and bootloader checks. Ofc you won't get the errors if your device isn't modified.

Excellent question! No idea what it checks for, I don't have a unlocked bootloader and I'm running an OEM ROM so unless I've been targeted with very advanced malware I shouldn't have a modified system and I'm just a depressed trans girl spending most of her day in her bed, not the most likely victim of such advanced malware. I even tried uninstalling shizuku along with any apps with "root" or "posed" in the name based on what some were reporting.

Now that I think about it, could be because I changed `database_creation_buildid` in the global table, though the change doesn't show up anywhere except the global table, but I can't be bothered to check.

**Comment by sdrgeek** [comment]
ok, enough input for merge imo @Crazyphil

**Comment by mavethee** [comment]
Hi, I've Installed Magidisk, LSPosed and apk from releases, loaded and rebooted. mObywatel still complains about root, sometimes on launch, sometimes after bank verification.
