### ISSUE TITLE
No Success with Digitales Amt v2.5.2

### ISSUE THREAD

**Issue by SeriousM** [Crazyphil/digitales-amt-liberator#2]
Hi, I just tried so many ways to get the DA running, including your addon.
The DA is in version 2.5.2 but sadly it does complain about the detected rooting.
I found another addon that worked with the version 2.5.2: https://github.com/SapuSeven/Digitales-Amt-Integrity-Bypass
Maybe you want to adapt the solution?

The difference is that you're using (https://github.com/Crazyphil/digitales-amt-liberator/blob/main/app/src/main/java/it/kapfer/digitalesamt/liberator/ModuleMain.kt#L36)
```
XposedHelpers.findAndHookMethod(DEVICE_INTEGRITY_CHECK_CLASS, lpparam.classLoader, "checkIntegrity", XC_MethodReplacement.DO_NOTHING)
```
which ends up in the function implementation (https://github.com/LSPosed/LSPosed/blob/master/core/src/main/java/de/robv/android/xposed/XC_MethodReplacement.java#L82)
```
    public static final XC_MethodReplacement DO_NOTHING = new XC_MethodReplacement(PRIORITY_HIGHEST * 2) {
        @Override
        protected Object replaceHookedMethod(MethodHookParam param) throws Throwable {
            return null;
        }
    };
```

and @Crazyphil uses (https://github.com/SapuSeven/Digitales-Amt-Integrity-Bypass/blob/master/app/src/main/java/com/sapuseven/xposed/at/gv/oe/app/RootBypass.kt#L18)
```
            object : XC_MethodReplacement() {
                @Throws(Throwable::class)
                override fun replaceHookedMethod(param: MethodHookParam) {
                    param.result = null
                }
            })
```

Setting "para.result = null" seems to be the solution and in fact is probably a guard against the use of `XC_MethodReplacement.DO_NOTHING`.

**Comment by Crazyphil** [comment]
Thank you for your in-depth analysis. Unfortunately, I cannot reproduce the problems you're having. I also use *Digitales Amt* in version 2.5.2, and *Digitales Amt Liberator* version 1.1.0 does its job just fine.

Just to confirm, these are my settings:

*Magisk* is installed in version 25.2
![magisk-version](https://user-images.githubusercontent.com/3602847/221809970-3c4dc6e4-6971-43d6-adbe-f78f10c7a37b.jpeg)

The *Digitales Amt* app is **not** denylisted in *Magisk*
![denylist](https://user-images.githubusercontent.com/3602847/221811645-bd1c63f8-3199-453f-86e8-f929172e6d5b.jpeg)

The *Zygisk* variant of *LSPosed* is installed in version 1.8.6 and enabled as a *Magisk* module
![magisk-modules](https://user-images.githubusercontent.com/3602847/221812578-a288c76a-6fb9-4879-b453-65986694662a.jpeg)
![lsposed](https://user-images.githubusercontent.com/3602847/221812781-080d3ff6-b4fa-4eb0-a7ae-695352899cac.jpeg)

*Digitales Amt Liberator* is installed and enabled in *LSPosed*
![lsposed-module](https://user-images.githubusercontent.com/3602847/221813425-1768d07f-86fb-4074-ad51-d6eaf685c1fc.jpeg)

*Digitales Amt Liberator* is enabled for the *Digitales Amt* app
![module-settings](https://user-images.githubusercontent.com/3602847/221813691-7ce37938-9618-4570-9d2d-9515c1c83f27.jpeg)


---
Regarding your comments to the code: whether you return a value or directly set the result parameter of a replaced method doesn't matter. At least that is what I deduced from the Javadoc and behavior of the `DO_NOTHING` hook.

If you look into the API source, you'll see that `setResult()` does nothing more than preventing the call of the original method and setting the result field (which is already initialized with `null` from the beginning):
```
		public void setResult(Object result) {
			this.result = result;
			this.throwable = null;
			this.returnEarly = true;
		}
```
https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XC_MethodHook.java#L96

The Javadoc confirms that it doesn't matter whether the result is set or simply returned for a replaced method:
```
	/**
	 * Shortcut for replacing a method completely. Whatever is returned/thrown here is taken
	 * instead of the result of the original method (which will not be called).
	 *
	 * <p>Note that implementations shouldn't call {@code super(param)}, it's not necessary.
	 *
	 * @param param Information about the method call.
	 * @throws Throwable Anything that is thrown by the callback will be passed on to the original caller.
	 */
	@SuppressWarnings("UnusedParameters")
	protected abstract Object replaceHookedMethod(MethodHookParam param) throws Throwable;
```
https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XC_MethodReplacement.java#L51

**Comment by SeriousM** [comment]
Thank you for all the information!
I can confirm that all versions are exactly the same on my phone.
The only difference I spotted is that LSPosed's "Xposed API-Aufrufschutz" is deactivated in oposion to your activated state.

I'm afraid that I wont check out if your version may work anyway because I already setup DA with my personal id and I don't wont go through reset - resetup everything.

> Regarding your comments to the code: whether you return a value or directly set the result parameter of a replaced method doesn't matter. At least that is what I deduced from the Javadoc and behavior of the `DO_NOTHING` hook.

What I wanted to point out, no matter if this makes the difference in successful patching, is that if the caller of the replaced method sets param.result to something known and expects that it doesn't get replaced with null, a null value would give away that that the method was actually replaced.

Anyway, I will close the issue and thank you very much for your investigation.
