### ISSUE TITLE
SPB Serviceportal Bund | Version 1.7.10 not working

### ISSUE THREAD

**Issue by Talki1** [Crazyphil/digitales-amt-liberator#20]
Dear Crazyphil!
I'm using your tool (Version 2.1) with LSPosed (API 100, Framework 1.0 (7066), System 14 (API 34)), and it worked perfect. After doing some updates (OS from 20240723 to 21-20240730-NIGHTLY-fajita), the app SPB Serviceportal Bund (Version 1.7.10; maybe I've updated this too) is not working anymore (device rooted). The app is not blocklisted by Magisk and activated in your Liberator. Digitales Amt (Version 3.2.0) is still working.
The logfile says:
`[ 2024-07-31T13:40:30.965    10211:  3893:  3893 I/LSPosed-Bridge  ] Loading legacy module it.kapfer.digitalesamt.liberator from /data/app/~~yNEZ3Ak5ajqvM_8XC8kZdw==/it.kapfer.digitalesamt.liberator-6aQIk7xyeHVifRkrasskNQ==/base.apk
[ 2024-07-31T13:40:30.988    10211:  3893:  3893 I/LSPosed-Bridge  ]   Loading class it.kapfer.digitalesamt.liberator.ModuleMain
[ 2024-07-31T13:40:31.088    10211:  3893:  3893 I/LSPosed-Bridge  ] Detected Digitales Amt
[ 2024-07-31T13:40:31.105    10211:  3893:  3893 I/LSPosed-Bridge  ] Hooking DeviceIntegrityCheck
[ 2024-07-31T13:42:16.586    10275:  7191:  7191 I/LSPosed-Bridge  ] Loading legacy module it.kapfer.digitalesamt.liberator from /data/app/~~yNEZ3Ak5ajqvM_8XC8kZdw==/it.kapfer.digitalesamt.liberator-6aQIk7xyeHVifRkrasskNQ==/base.apk
[ 2024-07-31T13:42:16.700    10275:  7191:  7191 I/LSPosed-Bridge  ]   Loading class it.kapfer.digitalesamt.liberator.ModuleMain
[ 2024-07-31T13:42:16.978    10275:  7191:  7191 I/LSPosed-Bridge  ] Detected Serviceportal Bund
[ 2024-07-31T13:42:16.981    10275:  7191:  7191 I/LSPosed-Bridge  ] Hooking DeviceIntegrityCheck `
Is there anything I can do - except hoping you'll find a way to fix it?
Best regards
Peter

**Comment by Crazyphil** [comment]
I will merge and create a new release next week after my vacation.

**Comment by sdrgeek** [comment]
If you need a build asap, here's my test APK: ![app-debug_20240801174155.apk.zip](https://github.com/user-attachments/files/16458870/app-debug_20240801174155.apk.zip)
