### ISSUE TITLE
Add George Österreich | question regarding non govt apps

### ISSUE THREAD

**Issue by sdrgeek** [Crazyphil/digitales-amt-liberator#25]
Hi @Crazyphil, I started reversing at.erstebank.george as it recently started detecting my modified device.
![Screenshot_20240908-131215_George.png](https://github.com/user-attachments/assets/a4bb16c0-937c-431b-9b67-2a0167333ae8)

Since there are multiple requests to add non govt apps to the e-government liberator project, I am thinking about forking this project to add non govt apps, such as George. I'm interested in hearing your opinion on that.

**Comment by Crazyphil** [comment]
Well, the module's name kind of evolved organically, so I'm not opposed to adding non-e-government apps as well. No need to fork, you can just make a pull request to add support for George 😉 Oh, and if you like you could also look at George CZ as requested in #16, maybe they share the same mechanism and can both be supported at once.

**Comment by sdrgeek** [comment]
I'll try. George is the most complicated yet. it even has hook checks....

**Comment by sdrgeek** [comment]
Turns out george didn't change at all, it always had this kind of detection. The problem rather was that i switched from CrDroid to LineageOS and didn't realise that LOS doesn't have playstore spoofing baked into the rom. Therefore MicroG wasn't able to spoof the signature and the app wouldn't work. 

Note: you can either install an [Xposed module](https://github.com/whew-inc/FakeGApps)  (and use **root installer** in Aurora store, as google is once again messing with us. Otherwise it wont work. ) or [fix it manually in shell](https://www.reddit.com/r/Austria/comments/p8qd8y/wie_man_die_george_app_auch_ohne_google_play_zum/).
