### ISSUE TITLE
support 

### ISSUE THREAD

**Issue by roadstrum** [Crazyphil/digitales-amt-liberator#5]
Thanks a lot for providing this module, it works like a charm, finaly I can use "Digitales Amt" under LineageOS.
It would be great, if you could make "Serviceportal Bund" (https://play.google.com/store/apps/details?id=at.gv.bka.serviceportal) work too. The checks seems similar, it detects root-Access and unlocked Bootloader on startup. Thanks again for your great work!

**Comment by Crazyphil** [comment]
I've added support for the app in PR #6.
Could you please download the [attached APK file](https://github.com/Crazyphil/digitales-amt-liberator/pull/6#issuecomment-1665199288) and test whether it works on your device?

Please uninstall the previous version of the Xposed module first and install the downloaded APK afterwards, as this is a debug build that is not compatible with the released version. When the module works for you, I will release a new version that can be downloaded as usual. To update to this version after that, you will have to uninstall the debug version first.

**Comment by roadstrum** [comment]
I've updated everything, and it seems to work, at least the app starts without detecting any root-access or unlocked bootloader. I can't test it fully, because the whole system is offline over the weekend (04.-07.08.2023: software-update of PM-SAP procedure). I will test it on Monday.

**Comment by roadstrum** [comment]
Thanks for supporting "Serviceportal Bund", your module is working perfect! The Serviceportal Bund app itself is a little bit buggy, but that seems to be normal and is not related to the Xposed module.
