### ISSUE TITLE
Cannot register card in edu.digicard

### ISSUE THREAD

**Issue by Crazyphil** [Crazyphil/digitales-amt-liberator#9]
> edu.digicard only partly works, as i get HTTP error 400: Bad request , when trying to import my digicard. My suspicion is, bmbfw checks whether the attestation challenge extension is present

_Originally posted by @sdrgeek in https://github.com/Crazyphil/digitales-amt-liberator/issues/7#issuecomment-1694726317_

**Comment by sdrgeek** [comment]
Had another look at edu.digicard. I can patch the app so it doesn't complain anymore but I cannot spoof the server. This is what I found out by intercepting the apps traffic: The server sends an attestation challenge and it seems like it actually checks the response. The Server always returns HTTP 400 and therefore I don't get my cert. I don't think this is fixable.

**Comment by Crazyphil** [comment]
Well, seems like that's settled, then: the module does what it promises, to remove root and bootloader checks. Server-side validation is out-of-scope. Although I still wonder whether that means that this app then isn't usable at all on devices without hardware key attestation, given that the server seems to rely on it.
